export const REQUEST_BLOG_POSTS = 'REQUEST_BLOG_POSTS'

export const FETCH_BLOG_POSTS = 'FETCH_BLOG_POSTS'
export const FETCH_BLOG_POSTS_SUCCESS = 'FETCH_BLOG_POSTS_SUCCESS'
export const FETCH_BLOG_POSTS_FAILURE = 'FETCH_BLOG_POSTS_FAILURE'
